### PR TITLE
Added dropdown menus

### PR DESCRIPTION
**Pull request by Gkrumbach07**
## Related Issues and Dependencies
https://github.com/thoth-station/jupyterlab-requirements/issues/63

## This introduces a breaking change

- [X] No

## This Pull Request implements

- info dropdown on package select (lets user know if they typed in a valid package)
- version dropdown for packages that Thoth knows about
   - A way to add constraints for multiple versions through a UI rather than a textbox

### CODE REVIEW

**Review by pacospace — COMMENTED** [review]
Please make pre-commit happy, otherwise lgtm! 💯 Thanks!!

**Comment by Gkrumbach07** [comment]
pre-commit fails on `black-nb`. I found in one other recent (less than a day) issue that someone had the same problem. I believe the latest version on `black-nb` is causing the error. Also this commit has no py files.

**Comment by pacospace** [comment]
> pre-commit fails on `black-nb`. I found in one other recent (less than a day) issue that someone had the same problem. I believe the latest version on `black-nb` is causing the error. Also this commit has no py files.

I see this also beside black issue

```
[INFO] Installing environment for https://gitlab.com/PyCQA/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Passed
Trim Trailing Whitespace.................................................Passed
Check for merge conflicts................................................Passed
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook
Fixing src/components/dependencyManagementConstraintPicker.tsx
Fixing style/icons/info.svg

```

**Comment by pacospace** [comment]
> pre-commit fails on `black-nb`. I found in one other recent (less than a day) issue that someone had the same problem. I believe the latest version on `black-nb` is causing the error. Also this commit has no py files.

cc @harshad16 have you seen that problem already? do we need to update the base image for pre-commit for prow?

**Comment by pacospace** [comment]
hey @Gkrumbach07 can you try modifying the .prow.yaml and use v0.14.3 in https://github.com/thoth-station/jupyterlab-requirements/blob/024e441b3c4947dbf4df8900120fadde38644cc1/.prow.yaml#L9?

**Comment by harshad16** [comment]
> have you seen that problem already? do we need to update the base image for pre-commit for prow?

I m trying to check on this issue and try to find the issue based on the investigation.

**Comment by pacospace** [comment]
Thanks @harshad16 for fixing it! @Gkrumbach07 can you please rebase on the merge PR fixing pre-commit?

**Review by pacospace — APPROVED** [review]
Thanks 💯 very nice feature!!

**Pull request merged**
