### PR TITLE
Move cachedir pipenv

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/jupyterlab-requirements/issues/201

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

As suggested by @fridex, let's move that cache dir to avoid issues with memory limits in the cluster for the container.

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm

Thanks for the addition :100:

**Comment by pacospace** [comment]
when setting that variable in subprocess.run, the command cannot run
```
Traceback (most recent call last):
  File "test.py", line 54, in <module>
    subprocess.run(["pipenv", "lock"], env={"PIPENV_CACHE_DIR": "/tmp"})
  File "/usr/lib64/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pipenv'
```

**Comment by fridex** [comment]
> when setting that variable in subprocess.run, the command cannot run
> 
> ```
> Traceback (most recent call last):
>   File "test.py", line 54, in <module>
>     subprocess.run(["pipenv", "lock"], env={"PIPENV_CACHE_DIR": "/tmp"})
>   File "/usr/lib64/python3.8/subprocess.py", line 489, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/usr/lib64/python3.8/subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'pipenv'
> ```

Was pipenv installed and available?

**Comment by pacospace** [comment]
> > when setting that variable in subprocess.run, the command cannot run
> > ```
> > Traceback (most recent call last):
> >   File "test.py", line 54, in <module>
> >     subprocess.run(["pipenv", "lock"], env={"PIPENV_CACHE_DIR": "/tmp"})
> >   File "/usr/lib64/python3.8/subprocess.py", line 489, in run
> >     with Popen(*popenargs, **kwargs) as process:
> >   File "/usr/lib64/python3.8/subprocess.py", line 854, in __init__
> >     self._execute_child(args, executable, preexec_fn, close_fds,
> >   File "/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child
> >     raise child_exception_type(errno_num, err_msg, err_filename)
> > FileNotFoundError: [Errno 2] No such file or directory: 'pipenv'
> > ```
> 
> Was pipenv installed and available?

I just tested that, it seems it does not find pipenv, but it is installed in my machine.

**Comment by pacospace** [comment]
> > > when setting that variable in subprocess.run, the command cannot run
> > > ```
> > > Traceback (most recent call last):
> > >   File "test.py", line 54, in <module>
> > >     subprocess.run(["pipenv", "lock"], env={"PIPENV_CACHE_DIR": "/tmp"})
> > >   File "/usr/lib64/python3.8/subprocess.py", line 489, in run
> > >     with Popen(*popenargs, **kwargs) as process:
> > >   File "/usr/lib64/python3.8/subprocess.py", line 854, in __init__
> > >     self._execute_child(args, executable, preexec_fn, close_fds,
> > >   File "/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child
> > >     raise child_exception_type(errno_num, err_msg, err_filename)
> > > FileNotFoundError: [Errno 2] No such file or directory: 'pipenv'
> > > ```
> > 
> > 
> > Was pipenv installed and available?
> 
> I just tested that, it seems it does not find pipenv, but it is installed in my machine.

It works correctly without that env variable, as soon as I introduce that env, it cannot find pipenv anymore. I'm confused on this behaviour, is it expecting pipenv installed in `/tmp`? @fridex

**Comment by pacospace** [comment]
> > > > when setting that variable in subprocess.run, the command cannot run
> > > > ```
> > > > Traceback (most recent call last):
> > > >   File "test.py", line 54, in <module>
> > > >     subprocess.run(["pipenv", "lock"], env={"PIPENV_CACHE_DIR": "/tmp"})
> > > >   File "/usr/lib64/python3.8/subprocess.py", line 489, in run
> > > >     with Popen(*popenargs, **kwargs) as process:
> > > >   File "/usr/lib64/python3.8/subprocess.py", line 854, in __init__
> > > >     self._execute_child(args, executable, preexec_fn, close_fds,
> > > >   File "/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child
> > > >     raise child_exception_type(errno_num, err_msg, err_filename)
> > > > FileNotFoundError: [Errno 2] No such file or directory: 'pipenv'
> > > > ```
> > > 
> > > 
> > > Was pipenv installed and available?
> > 
> > 
> > I just tested that, it seems it does not find pipenv, but it is installed in my machine.
> 
> It works correctly without that env variable, as soon as I introduce that env, it cannot find pipenv anymore. I'm confused on this behaviour, is it expecting pipenv installed in `/tmp`? @fridex

maybe is `env` in subprocess.run

**Comment by pacospace** [comment]
> > > > > when setting that variable in subprocess.run, the command cannot run
> > > > > ```
> > > > > Traceback (most recent call last):
> > > > >   File "test.py", line 54, in <module>
> > > > >     subprocess.run(["pipenv", "lock"], env={"PIPENV_CACHE_DIR": "/tmp"})
> > > > >   File "/usr/lib64/python3.8/subprocess.py", line 489, in run
> > > > >     with Popen(*popenargs, **kwargs) as process:
> > > > >   File "/usr/lib64/python3.8/subprocess.py", line 854, in __init__
> > > > >     self._execute_child(args, executable, preexec_fn, close_fds,
> > > > >   File "/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child
> > > > >     raise child_exception_type(errno_num, err_msg, err_filename)
> > > > > FileNotFoundError: [Errno 2] No such file or directory: 'pipenv'
> > > > > ```
> > > > 
> > > > 
> > > > Was pipenv installed and available?
> > > 
> > > 
> > > I just tested that, it seems it does not find pipenv, but it is installed in my machine.
> > 
> > 
> > It works correctly without that env variable, as soon as I introduce that env, it cannot find pipenv anymore. I'm confused on this behaviour, is it expecting pipenv installed in `/tmp`? @fridex
> 
> maybe is `env` in subprocess.run

Yes using `env=dict(os.environ, PIPENV_CACHE_DIR='/tmp')` worked!

**Pull request merged**
